# Generated by Django 5.2.3 on 2025-06-22 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_logs', to='accounts.pharmacist')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_logs', to='medical.prescription')),
            ],
        ),
    ]
