name: meditrack
description: Production-ready medical app with Patient, Doctor, Pharmacist roles.

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  # intl: ^0.19.0   # <-- احذف هذا السطر أو علّق عليه بالـ #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/meditrackLogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/meditrackLogo.png
    - assets/splash/meditrack_splash.png